[project]
name = "fpl-points-prediction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jinja2>=3.1.6",
    "jupyter>=1.1.1",
    "logging>=0.4.9.6",
    "pandas>=3.0.1",
    "pydantic>=2.13.4",
    "pygithub>=2.8.1",
]
