filenames: 
  - "teams"
  - "players"
  - "playerstats"
  - "matches"
  - "playermatchstats"

temporal_granularity: 
  - "static"
  - "season"
  - "gameweek"

filepath_jinja: # expressed in jinja template format
  structure_0: >- # 2024-2025
    fpl-core-insights/{{ season }}/{{ filename }}/{% if temporal_granularity == 'gameweek' %}GW{{ gameweek }}/{% endif %}{{ filename }}.csv
    
  structure_1: >- # 2025-2026
    fpl-core-insights/{{ season }}/{% if temporal_granularity == 'gameweek' %}By Gameweek/GW{{ gameweek }}/{% endif %}{{ filename }}.csv

season_filepath_jinja_map: # seasons in structure "YYYY-YYYY"
  2024-2025: "structure_0"
  2025-2026: "structure_1"